---


- include: create_swap_file.yml
  when: create_swap_file
  tags: swap


- name: set env en_US.UTF-8
  lineinfile: dest=/root/.bash_profile line='export LC_ALL="en_US.UTF-8"' state=present create=yes

- name: gen env en_US.UTF-8
  shell: locale-gen en_US.UTF-8

- name: update env en_US.UTF-8
  shell: update-locale en_US.UTF-8

- name: 使用阿里云的源
  action: template src=../templates/sources_list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

- name: 使用阿里云的容器镜像
  action: template src=../templates/docker-daemon.json.j2 dest=/etc/docker/daemon.json owner=root group=root mode=0644

- name: reload 相关服务
  shell: systemctl daemon-reload && systemctl restart docker

# Setup hostname

- name: setup hostname
  hostname: name={{ inventory_hostname }}

- name: setup hosts file
  lineinfile: dest=/etc/hosts line="127.0.0.1       {{ inventory_hostname }}" backup=yes

# Setup default DNS

- name: setup 114 dns
  lineinfile: dest=/etc/resolv.conf line="nameserver 114.114.114.114" backup=yes

- name: set google dns
  lineinfile: dest=/etc/resolv.conf line="nameserver 8.8.8.8" backup=yes


- name: Update all packages to the latest stable version
  apt: upgrade=dist

- name: Update update_cache
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure bash,zsh , OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - zsh
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - acl
    - build-essential
    - curl
    - git
    - git-core
    - vim
    - supervisor
    - docker.io
  tags:
    - packages

